---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install -g npm@latest
    sudo npm install pm2 -g
    sudo npm install -g webpack-dev-server
