---
  - name: "Creates backend directory"
    file:
      path: ~/backend-app
      state: directory
      mode: 0755
      
  - name: "Unarchive backend files"
    unarchive:
      src: artifact.tar.gz
      dest: ~/backend-app
      mode: 0755
      owner: ubuntu
      group: ubuntu

  - name: "Installing dependencies"
    shell: |
      cd ~/backend-app
      npm i

  - name: "Executing Node app with PM2"
    shell: |
      cd ~/backend-app/dist
      pm2 stop default
      pm2 start main.js 

  - name: "Configure pm2 to start as service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp  /home/ubuntu
