---
  - name: "Creates backend directory"
    file:
      path: ~/backend
      state: directory
      mode: 0755
      
  - name: "Unarchive backend files"
    unarchive:
      src: ~/project/artifact.tar.gz
      dest: ~/backend
      mode: 0755
      owner: ubuntu
      group: ubuntu

  - name: "Installing dependencies"
    shell: |
      cd backend
      curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      sudo apt install -y nodejs
      sudo npm install -g npm@latest
      sudo npm install -g webpack-dev-server
      sudo npm install
      sudo npm run build
      sudo pm2 start npm --name backend -- start
