---
  - name: "Copy Backend file"
    copy:
      path: artifact.tar.gz
      dest: /home/ubuntu
      
  - name: "unarchive backend files"
    ansible.builtin.shell: tar -xzf artifact.tar.gz
    args: 
      chdir: /home/ubuntu

  - name: "Installing Node node"
    shell: |
      cd /home/ubuntu/backend
      npm i

  - name: "Executing Node app with PM2"
    shell: |
      cd /home/ubuntu/backend
      pm2 stop default
      pm2 start main.js
    register: execute_node
  
  - name: "print message"
    debug:
      msg: "{{ execute_node.stdout_lines }}"

  - name: "Configure pm2 to start as service"
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp  /home/ubuntu
